### PR TITLE
Add support for Windows installation

### PR DESCRIPTION
**Pull request by darioncassel**
## Description

Added `z3.lib` to the binaries directory for Windows installation and added a `build.rs` file to allow Rust to locate the lib on Windows. Updated `InstallationGuide.md` to reflect this. Added Windows to   `.travis.yml` build matrix.

(Also changed "OSX" to "macOS" in `InstallationGuide.md` to reflect official renaming).

Fixes: N/A

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] API change with a documentation update
- [ ] Additional test coverage

## How Has This Been Tested?

Installation with the change has been tested locally on both a Windows and on a macOS machine.

## Checklist:

- [x] Fork the repo and create your branch from `master`.
- [ ] If you've added code that should be tested, add tests.
- [ ] If you've changed APIs, update the documentation.
- [x] Ensure the test suite passes.
- [x] Make sure your code lints.
- [x] If you haven't already, complete your CLA here: <https://code.facebook.com/cla>

### CODE REVIEW

**Comment by darioncassel** [comment]
The checks passed but the Windows build still timed out and was terminated so we don't know for sure that it works (besides already done local testing).

**Comment by hermanventer** [comment]
Since the Windows build doesn't do anything useful, we may as well remove it from the test matrix.

**Comment by darioncassel** [comment]
That makes sense. Do we still want to include the Windows support changes if they can't be tested via Travis?

**Comment by hermanventer** [comment]
Yes, let's keep it. Hopefully people using it will let us know if it breaks.

**Comment by darioncassel** [comment]
Ok, I will revert the Travis changes and leave the rest.

**Pull request merged**
